triggers:
  getTriggers:
    200:
      description: "fetched all triggers"
      content:
        application/json:
          schema:
            type: object
            properties:
              list:
                type: array
                description: "list of available triggers"
                items:
                  $ref: "../shared/schemas/Trigger.yml#/Trigger"

  createTrigger:
    200:
      description: "Trigger created"
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                example: trigger_id
              message:
                type: string
                example: trigger created
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

trigger:
  deleteTrigger:
    200:
      description: "Trigger has been deleted"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

  updateTrigger:
    200:
      description: "Trigger updated"
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                example: trigger_id
              message:
                type: string
                example: trigger created
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

  getTrigger:
    200:
      description: "Trigger data"
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/Trigger.yml#/Trigger"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"
    404:
      $ref: "../shared/responses/_index.yml#/NotFound"

pageTriggers:
  200:
    description: "fetched matching triggers"
    content:
      application/json:
        schema:
          type: object
          properties:
            page:
              type: number
              description: "current item page"
              example: 0
            size:
              type: number
              description: "number of triggers shown per page"
              example: 10
            total:
              type: number
              description: "total number of matching results"
              example: 5
            list:
              type: array
              description: "list of matching triggers"
              items:
                $ref: "../shared/schemas/Trigger.yml#/Trigger"

searchTriggers:
  200:
    description: "fetched matching triggers"
    content:
      application/json:
        schema:
          type: object
          properties:
            page:
              type: number
              description: "current item page"
              example: 0
            size:
              type: number
              description: "number of triggers shown per page"
              example: 10
            total:
              type: number
              description: "total number of matching results"
              example: 5
            list:
              type: array
              description: "list of matching triggers"
              items:
                $ref: "../shared/schemas/Trigger.yml#/Trigger"
