openapi: 3.0.0
info:
  description: "This is an API description for Moira Alert project. Please check https://github.com/moira-alert"
  version: "2.5.1"
  title: "Moira Alert"
  # contact:
  #   link: "https://t.me/moira_alert"
  license:
    name: "MIT"
servers:
  - url: http://localhost:8080/api
    description: Localhost server
paths:
  /trigger:
    $ref: ./triggers/methods.yml
